    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qltv;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static javax.swing.text.html.HTML.Tag.SELECT;

/**
 *
 * @author May May
 */
public class Thuthu extends javax.swing.JFrame {

    /**
     * Creates new form Thuthu
     */
    public Thuthu() {
        initComponents();
        napThuThu();
        ImageIcon im  = new ImageIcon("C:\\Users\\vanth\\Desktop\\icon java/adminicon.png");
        setIconImage(im.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel_MTT = new javax.swing.JLabel();
        jLabel_Ho = new javax.swing.JLabel();
        jLabel_Ten = new javax.swing.JLabel();
        jLabel_Phai = new javax.swing.JLabel();
        jLabel_DiaChi = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_Sdt = new javax.swing.JLabel();
        jLabel_TT = new javax.swing.JLabel();
        jTextField_Ho = new javax.swing.JTextField();
        jTextField_Ten = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_Sdt = new javax.swing.JTextField();
        jTextField_MTT = new javax.swing.JTextField();
        jButton_Luu = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jRadioButton_Nam = new javax.swing.JRadioButton();
        jRadioButton_Nu = new javax.swing.JRadioButton();
        jButton_Exit = new javax.swing.JButton();
        jPanel_T = new javax.swing.JPanel();
        jScrollPane_ThuThu = new javax.swing.JScrollPane();
        jTable_ThuThu = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextField_DiaChi = new javax.swing.JTextField();

        jScrollPane2.setViewportView(jTextPane2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ THỦ THƯ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel_MTT.setText("MÃ THỦ THƯ:");

        jLabel_Ho.setText("HỌ:");

        jLabel_Ten.setText("TÊN:");

        jLabel_Phai.setText("PHÁI:");

        jLabel_DiaChi.setText("ĐỊA CHỈ:");

        jLabel_Email.setText("EMAIL:");

        jLabel_Sdt.setText("SĐT:");

        jLabel_TT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jLabel_TT.setText("QUẢN LÝ THỦ THƯ");

        jTextField_Ho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_HoActionPerformed(evt);
            }
        });

        jTextField_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EmailActionPerformed(evt);
            }
        });

        jButton_Luu.setText("Lưu");
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });

        jButton_Xoa.setText("Xóa");
        jButton_Xoa.setMaximumSize(new java.awt.Dimension(65, 25));
        jButton_Xoa.setMinimumSize(new java.awt.Dimension(65, 25));
        jButton_Xoa.setPreferredSize(new java.awt.Dimension(65, 25));
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_Nam);
        jRadioButton_Nam.setSelected(true);
        jRadioButton_Nam.setText("Nam");
        jRadioButton_Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_NamActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_Nu);
        jRadioButton_Nu.setText("Nữ");
        jRadioButton_Nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_NuActionPerformed(evt);
            }
        });

        jButton_Exit.setText("Đăng xuất");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jTable_ThuThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thủ thư", "Họ", "Tên", "Phái", "Địa chỉ", "Email", "Số điện thoại"
            }
        ));
        jTable_ThuThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ThuThuMouseClicked(evt);
            }
        });
        jScrollPane_ThuThu.setViewportView(jTable_ThuThu);

        jLabel10.setText("DANH SÁCH:");

        javax.swing.GroupLayout jPanel_TLayout = new javax.swing.GroupLayout(jPanel_T);
        jPanel_T.setLayout(jPanel_TLayout);
        jPanel_TLayout.setHorizontalGroup(
            jPanel_TLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_TLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_ThuThu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                    .addGroup(jPanel_TLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_TLayout.setVerticalGroup(
            jPanel_TLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane_ThuThu, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton_Luu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel_MTT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Ten)
                    .addComponent(jLabel_DiaChi)
                    .addComponent(jLabel_Ho))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_MTT, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(jTextField_Ho)
                                    .addComponent(jTextField_Ten))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Email)
                                    .addComponent(jLabel_Phai)
                                    .addComponent(jLabel_Sdt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton_Nam)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton_Nu))
                                    .addComponent(jTextField_Sdt, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(jTextField_Email)))
                            .addComponent(jTextField_DiaChi))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Exit)
                        .addGap(62, 62, 62))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel_TT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_TT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_MTT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_MTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Ho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Ho))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Ten)
                            .addComponent(jTextField_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Phai)
                            .addComponent(jRadioButton_Nam)
                            .addComponent(jRadioButton_Nu))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Email)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Sdt)
                            .addComponent(jTextField_Sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_DiaChi)
                    .addComponent(jTextField_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Luu)
                    .addComponent(jButton_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Exit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean trungEmail(String email, String MATT)
    {
        Connection connect = ketnoicsdl.layKetNoi();
        try
        {
            Statement st = connect.createStatement();
            ResultSet rs = st.executeQuery("SELECT EMAIL FROM THUTHU WHERE EMAIL = '" + email + "' AND MATT <> '" + MATT + "'");
        //    System.out.println("SELECT EMAIL FROM THUTHU WHERE EMAIL = '" + email + "' AND MATT <> '" + MATT + "'");
            while (rs.next())
            {
                return true;
            }
        }
        catch(SQLException e)
        {
            
        }
        return false;
    }
    private boolean trungSDT(String SDT, String MATT)
    {
        Connection connect = ketnoicsdl.layKetNoi();
        try
        {
            Statement st = connect.createStatement();
            ResultSet rs = st.executeQuery("SELECT SDT FROM THUTHU WHERE SDT = " + Integer.valueOf(SDT) + "AND MATT <> '" + MATT + "'");
            while (rs.next())
            {
                return true;
            }
        }
        catch(SQLException e)
        {
            
        }
        return false;
    }
    private boolean cothexoa(String MATT)
    {
        Connection connect = ketnoicsdl.layKetNoi();
        try
        {
            Statement st = connect.createStatement();
            ResultSet rs = st.executeQuery("SELECT MATT FROM PHIEUMUONSACH WHERE MATT = '" + MATT + "'");
            while (rs.next())
            {
                return true;
            }
        }
        catch(SQLException e)
        {
            
        }
        try
        {
            Statement st = connect.createStatement();
            ResultSet rs = st.executeQuery("SELECT MATTT FROM CTPHIEUMUON WHERE MATTT = '" + MATT + "'");
            while (rs.next())
            {
                return true;
            }
        }
        catch(SQLException e)
        {
            
        }
        return false;
    }
    public void napThuThu()
    {
        DefaultTableModel ntt = (DefaultTableModel) jTable_ThuThu.getModel();
        ntt.setNumRows(0);

        Connection connect = ketnoicsdl.layKetNoi();
        try
        {
            Statement st = connect.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM THUTHU");
            while(rs.next())
            {
             Vector<Object> vt = new Vector();
             String MATT = rs.getString("MATT");
             String HO = rs.getString("HO");
             String TEN = rs.getString("TEN");
             String PHAI = rs.getString("PHAI");
             String DIACHI = rs.getString("DIACHI");
             String EMAIL = rs.getString("EMAIL");
             int SDT = Integer.parseInt(rs.getString("SDT"));
             
             vt.add(MATT);
             vt.add(HO);
             vt.add(TEN);
             vt.add(PHAI);
             vt.add(DIACHI);
             vt.add(EMAIL);
             vt.add(SDT);
             //   System.out.println(vt);
             ntt.addRow(vt);
            }
        }
        catch (SQLException e)
        {
            System.out.println("Khong the nap thu thu");
        }
    }
    
    private void themThuThu(String MTT, String Ho, String Ten, String Phai, String DiaChi, String Email, String Sdt)
    {
        Connection ketNoi = ketnoicsdl.layKetNoi();
        String sql;
        sql = "insert into THUTHU values (?,?,?,?,?,?,?)";
        try
        {
            int SDT = Integer.valueOf(Sdt);
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ps.setString(1, MTT);
            ps.setString(2, Ho);
            ps.setString(3, Ten);
            ps.setString(4, Phai);
            ps.setString(5, DiaChi);
            ps.setString(6, Email);
            ps.setInt(7, SDT);
            ps.executeUpdate();
            
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
    
    private void suaThuThu(String MATT, String Ho, String Ten, String Phai, String DiaChi, String Email, String Sdt)
    {
        Connection connect = ketnoicsdl.layKetNoi();
        String st = "update THUTHU SET MATT=?, HO=?, TEN=?, PHAI=?, DIACHI=?, EMAIL=?, SDT=? WHERE MATT='"+MATT+"'";
        try
        {
            PreparedStatement ps = connect.prepareStatement(st);
            ps.setString(1, MATT);
            ps.setString(2, Ho);
            ps.setString(3, Ten);
            ps.setString(4, Phai);
            ps.setString(5, DiaChi);
            ps.setString(6, Email);
            ps.setString(7, Sdt);
            ps.executeUpdate();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
    
    
    private boolean kiemtraMATT(String MTT)
    { 
        Connection connect = ketnoicsdl.layKetNoi();
        try
        {
            Statement st = connect.createStatement();
            ResultSet rs = st.executeQuery("SELECT MATT FROM THUTHU WHERE MATT = '" + MTT + "'");
            while(rs.next())
            {
                return true;
            }
        }
        catch(Exception ex)
        {
            
        }
        return false;
    }
    
    private void xoatheoMATT(String MTT)
    {
        if (cothexoa(MTT)){JOptionPane.showMessageDialog(rootPane, "Không thể xóa thủ thư này do thủ thư đã cho mượn trả"); return;}
        Connection connect = ketnoicsdl.layKetNoi();
        String st= "delete THUTHU where MATT = '"+ MTT+"'";
        try
        {
            PreparedStatement ps = connect.prepareStatement(st);
            //ps.setString(1, MTT);
            ps.executeUpdate();
        }
        catch(Exception ex)
        {
            
        }
        JOptionPane.showMessageDialog(this, "Xóa thành công mã đã yêu cầu");
        this.napThuThu();
        jTextField_MTT.setText("");
        jTextField_Ho.setText("");
        jTextField_Ten.setText("");
        jTextField_DiaChi.setText("");
        jTextField_Email.setText("");
        jTextField_Sdt.setText("");
    }  
    
    public boolean checkEmail(String email)
    {
        String check = "^[a-z][a-z0-9]{0,}[@]{1}[a-z]{1,}\\.{1}[a-z]{1,}";
        return email.matches(check);
    }
    
    public boolean checkSdt(String sdt)
    {
        String check = "^[0][0-9]{9}";
        return sdt.matches(check);
    }
    
    private void jTextField_HoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_HoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_HoActionPerformed

    private void jTextField_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmailActionPerformed

    private void jRadioButton_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_NamActionPerformed

    private void jRadioButton_NuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_NuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_NuActionPerformed

    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuActionPerformed
        String MTT = jTextField_MTT.getText();
        String Ho = jTextField_Ho.getText();
        String Ten = jTextField_Ten.getText();
        String Phai = jRadioButton_Nam.isSelected() == true ? "Nam" : "Nữ";
        String Email = jTextField_Email.getText();
        String Sdt = jTextField_Sdt.getText();
        String DiaChi = jTextField_DiaChi.getText();
        // TODO add your handling code here:
        
        
        if(MTT.length()==0)
        {
            JOptionPane.showMessageDialog(this, "MTT chưa được hoàn thành!");
        }
        else if(Ho.length()==0)
        {
            JOptionPane.showMessageDialog(this, "Họ chưa được hoàn thành!");
        }
        else if(Ten.length()==0)
        {
            JOptionPane.showMessageDialog(this, "Tên chưa được hoàn thành!");
        }
        else if(Email.length()==0 || checkEmail(Email)!= true)
        {
            JOptionPane.showMessageDialog(this, "Email chưa được hoàn thành!, Yêu cầu nhập đúng định dạng: 'xxx@xxx.xxx");
        }
        else if(Sdt.length()==0 || checkSdt(Sdt)!=true)
        {
            JOptionPane.showMessageDialog(this, "Số điện thoại chưa được hoàn thành!, Yêu cầu nhập đúng định dạng: '0xxxxxxxxx'");
        }
        else if(DiaChi.length()==0)
        {
            JOptionPane.showMessageDialog(this, "Địa chỉ chưa được hoàn thành!");
        }
        else
        {
            if(kiemtraMATT(MTT)==true)
            {
                if (trungEmail(Email,MTT))
                {
                    JOptionPane.showMessageDialog(rootPane, "Email đã tồn tại");
                }
                else if (trungSDT(Sdt,MTT))
                {
                    JOptionPane.showMessageDialog(rootPane, "Số điện thoại đã tồn tại");
                }
                else
                {
                    int choose = JOptionPane.showConfirmDialog(this, "Mã trùng, bạn có muốn cập nhật lại mã không?");
                    if(choose == 0)
                    {
                        suaThuThu(MTT, Ho, Ten, Phai, DiaChi, Email, Sdt);
                        JOptionPane.showMessageDialog(this, "Cập nhật lại thủ thư thành công!");
                        jTable_ThuThu.removeAll();
                        napThuThu();
                        jTextField_MTT.setText("");
                        jTextField_Ho.setText("");
                        jTextField_Ten.setText("");
                        jTextField_DiaChi.setText("");
                        jTextField_Email.setText("");
                        jTextField_Sdt.setText("");
                    }
                }
            }
            else
            {
                if (trungEmail(Email,MTT))
                {
                    JOptionPane.showMessageDialog(rootPane, "Email đã tồn tại");
                }
                else if (trungSDT(Sdt,MTT))
                {
                    JOptionPane.showMessageDialog(rootPane, "Số điện thoại đã tồn tại");
                }
                else
                {
                    themThuThu(MTT, Ho, Ten, Phai, DiaChi, Email, Sdt);
                    JOptionPane.showMessageDialog(this, "Thêm thủ thư thành công!");
                    jTable_ThuThu.removeAll();
                    napThuThu();
                    jTextField_MTT.setText("");
                    jTextField_Ho.setText("");
                    jTextField_Ten.setText("");
                    jTextField_DiaChi.setText("");
                    jTextField_Email.setText("");
                    jTextField_Sdt.setText("");
                }
                    
            }
        }
        
        
        
    }//GEN-LAST:event_jButton_LuuActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        setVisible(false);
        removeAll();
        new login().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
         // TODO add your handling code here:
        String MTT = jTextField_MTT.getText();
        if(MTT.length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Nhập Mã thủ thư bạn muốn xóa");
        }
        else
        {
            if(kiemtraMATT(MTT)==true)
            {
                xoatheoMATT(MTT);
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Không tồn tại mã cần xóa");
            }
        }
        
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jTable_ThuThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ThuThuMouseClicked
        int i = jTable_ThuThu.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) jTable_ThuThu.getModel();
        
        String ns[]= dtm.getValueAt(i, 4).toString().split("-");
        
        jTextField_MTT.setText(dtm.getValueAt(i, 0).toString());
        jTextField_Ho.setText(dtm.getValueAt(i, 1).toString());
        jTextField_Ten.setText(dtm.getValueAt(i, 2).toString());
        if(dtm.getValueAt(i, 3).toString().equals("NAM"))
        {
            jRadioButton_Nam.setSelected(true);
        }
        else
        {
            jRadioButton_Nu.setSelected(true);
        }
        jTextField_DiaChi.setText(dtm.getValueAt(i, 4).toString());
        jTextField_Email.setText(dtm.getValueAt(i, 5).toString());
        jTextField_Sdt.setText("0" + dtm.getValueAt(i, 6).toString());
    }//GEN-LAST:event_jTable_ThuThuMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thoát?");
        if(check == 0) System.exit(0);
        else setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thuthu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thuthu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thuthu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thuthu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Thuthu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel_DiaChi;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Ho;
    private javax.swing.JLabel jLabel_MTT;
    private javax.swing.JLabel jLabel_Phai;
    private javax.swing.JLabel jLabel_Sdt;
    private javax.swing.JLabel jLabel_TT;
    private javax.swing.JLabel jLabel_Ten;
    private javax.swing.JPanel jPanel_T;
    private javax.swing.JRadioButton jRadioButton_Nam;
    private javax.swing.JRadioButton jRadioButton_Nu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane_ThuThu;
    private javax.swing.JTable jTable_ThuThu;
    private javax.swing.JTextField jTextField_DiaChi;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Ho;
    private javax.swing.JTextField jTextField_MTT;
    private javax.swing.JTextField jTextField_Sdt;
    private javax.swing.JTextField jTextField_Ten;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables

}